### ISSUE TITLE
Yosemiteでクラッシュする

### ISSUE THREAD

**Issue by geta6** [harukasan/butter#17]
クラッシュレポートはります

NotificationCenterのチップをクリックして部屋を変更しようとしたタイミングで発生する確率が高いです

**Comment by walf443** [comment]
YosemiteからだとWKWebkitというやつが使えるらしいので、WKWebkitを使うようにしてみたらどうかな (RubyMotionのSDKもってない...

**Comment by harukasan** [comment]
Butter 0.2.0から再発していないような気がするので一旦このissueを閉じます
