### ISSUE TITLE
Enterキーによるメッセージ送信の直後にRoomを切り替えると、切り替え後のRoomにメッセージが表示されてしまう

### ISSUE THREAD

**Issue by yasulab** [harukasan/butter#18]
idobata.io では再現しませんでしたが、Butterの方では再現したので報告します。

### 再現方法
1. メッセージをテキストフィールドに書き込む
2. Enterキーなどでメッセージを送信する (テキストフィールドがdisableになる)
3. メッセージが表示される前に (メッセージ送信直後に) Room を切り替える
4. 切り替え後の Room にメッセージが表示される

ただし、実際に idobata.io などを別ブラウザ/アプリで開いてメッセージ確認してみると、ちゃんと切り替え前のRoomにメッセージが表示されます。なので、盛大に誤爆することはないので安心ですが、一見誤爆したかのように見えるので、ちょっと焦っちゃいました :sweat_smile:

**Comment by ursm** [comment]
あいやー、これは Idobata のバグだと思います。ご不便をお掛けしますが次の大きいリリースで直るはずなのでしばしお待ちくださいませ。

**Comment by yasulab** [comment]
ありがとうございます!

**Comment by harukasan** [comment]
なるほど！Idobataのバグということでこのissueは一旦closeしますー
